# Generated by Django 4.1.7 on 2023-03-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_id',
            new_name='order',
        ),
    ]
