# Generated by Django 4.1.7 on 2023-03-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_orderdetails_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='apps.orders', verbose_name='ИД заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='apps.delivery', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='apps.pay', verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='apps.status', verbose_name='Статус'),
        ),
    ]
